### PR TITLE
Recognise Paperwhite 5.3.5 update magic number

### PR DESCRIPTION
**Pull request by bpfoley**

### CODE REVIEW

**Comment by NiLuJe** [comment]
FWIW, it's a bit more complex than that. My fork (https://github.com/NiLuJe/KindleTool) should support this new recovery format properly, at least for extraction (creation is supported, but untested since we'd need a custom kernel or amazon's private keys to actually successfully run such a custom recovery update package).

**Comment by bpfoley** [comment]
Ah I see, thanks for the pointer. Your fork looks much more up to date. I thought there was probably more to the update format change than just matching the magic number, but that was enough to let me extract the kernel & rootfs from the update, which was mostly what I was interested in.

**Comment by NiLuJe** [comment]
Yep, IIRC, the header & block size are the same between the two formats, so, yeah, that would be enough to pull the tarball out, it's mainly inside the header itself that things get a bit more complex ;).

**Comment by yifanlu** [comment]
Glad to see you guys have it figured out.

**Pull request closed without merging**
